import PptxGenJS from 'pptxgenjs';
import { generateTopicContent } from '../../topicGeneration/logic/api';
import { TopicResult } from '../../topicGeneration/types';
import { getBase64FromUrl } from './converter';

export const generatePptFromTopic = async (
  topic: string, 
  onProgress?: (status: string) => void
): Promise<void> => {
  try {
    // 1. Fetch content from AI
    onProgress?.('正在生成内容...');
    const results: TopicResult[] = await generateTopicContent(topic, '1024x576');

    if (!results || results.length === 0) {
      throw new Error('未能生成有效内容');
    }

    // 2. Initialize PPT
    onProgress?.('正在构建 PPT...');
    const pres = new PptxGenJS();
    pres.layout = 'LAYOUT_16x9';
    
    // Add Title Slide
    const titleSlide = pres.addSlide();
    titleSlide.background = { color: '1A1A1A' };
    titleSlide.addText(topic, {
      x: '10%', y: '40%', w: '80%', h: 1.5,
      fontSize: 44, color: 'FFFFFF', bold: true, align: 'center'
    });
    titleSlide.addText(`Generated by MediaPicGen`, {
      x: '10%', y: '60%', w: '80%', h: 0.5,
      fontSize: 14, color: 'AAAAAA', align: 'center'
    });

    // 3. Create slides from results
    for (let i = 0; i < results.length; i++) {
      const item = results[i];
      onProgress?.(`正在处理第 ${i + 1}/${results.length} 页...`);

      const slide = pres.addSlide();
      
      // Background Image
      if (item.uploadPath) {
        try {
          const base64 = await getBase64FromUrl(item.uploadPath);
          slide.background = { data: base64 };
          // Add a semi-transparent overlay to make text readable
          slide.addShape(pres.ShapeType.rect, {
            x: 0, y: 0, w: '100%', h: '100%',
            fill: { color: '000000', transparency: 60 }
          });
        } catch (e) {
          console.warn('Failed to load background image', e);
          slide.background = { color: '222222' };
        }
      } else {
        slide.background = { color: '222222' };
      }

      // Content Text
      // Split content into title and body if possible, or just dump it
      // Simple heuristic: First line is title if short?
      const lines = item.content.split('\n').filter(l => l.trim());
      let title = `Page ${i + 1}`;
      let body = item.content;

      if (lines.length > 0 && lines[0].length < 30) {
        title = lines[0];
        body = lines.slice(1).join('\n');
      }

      // Title
      slide.addText(title, {
        x: '5%', y: '5%', w: '90%', h: 1,
        fontSize: 32, color: 'FFFFFF', bold: true,
        shadow: { type: 'outer', color: '000000', blur: 3, offset: 2, opacity: 0.5 }
      });

      // Body
      slide.addText(body, {
        x: '5%', y: '20%', w: '90%', h: '70%',
        fontSize: 18, color: 'EEEEEE', 
        valign: 'top', align: 'left',
        shadow: { type: 'outer', color: '000000', blur: 2, offset: 1, opacity: 0.5 }
      });
    }

    // 4. Save
    onProgress?.('正在导出文件...');
    const fileName = `${topic.replace(/[\\/:*?"<>|]/g, '_')}_${new Date().getTime()}.pptx`;
    await pres.writeFile({ fileName });
    
    onProgress?.('完成!');
  } catch (error) {
    console.error('PPT Generation failed:', error);
    throw error;
  }
};
